CREATE TABLE mensagens (
  id bigint generated by default as identity,
  de text,
  texto varchar,
  created_at timestamp with time zone default now() not null,

  primary key (id)
);

alter table public.mensagens
  replica identity full;

begin;
  drop publication if exists supabase_realtime;
  create publication supabase_realtime;
commit;
alter publication supabase_realtime add table public.mensagens;